# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import core_app.grpc.pb.AgentTool_pb2 as AgentTool__pb2


class AgentToolControllerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateAgentTool = channel.unary_unary(
                '/pb.AgentToolController/CreateAgentTool',
                request_serializer=AgentTool__pb2.CreateAgentToolRequest.SerializeToString,
                response_deserializer=AgentTool__pb2.CreateAgentToolResponse.FromString,
                )
        self.GetAgentTool = channel.unary_unary(
                '/pb.AgentToolController/GetAgentTool',
                request_serializer=AgentTool__pb2.GetAgentToolRequest.SerializeToString,
                response_deserializer=AgentTool__pb2.GetAgentToolResponse.FromString,
                )
        self.ListAgentTools = channel.unary_unary(
                '/pb.AgentToolController/ListAgentTools',
                request_serializer=AgentTool__pb2.ListAgentToolsRequest.SerializeToString,
                response_deserializer=AgentTool__pb2.ListAgentToolsResponse.FromString,
                )
        self.UpdateAgentTool = channel.unary_unary(
                '/pb.AgentToolController/UpdateAgentTool',
                request_serializer=AgentTool__pb2.UpdateAgentToolRequest.SerializeToString,
                response_deserializer=AgentTool__pb2.UpdateAgentToolResponse.FromString,
                )
        self.DeleteAgentTool = channel.unary_unary(
                '/pb.AgentToolController/DeleteAgentTool',
                request_serializer=AgentTool__pb2.DeleteAgentToolRequest.SerializeToString,
                response_deserializer=AgentTool__pb2.DeleteAgentToolResponse.FromString,
                )


class AgentToolControllerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateAgentTool(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAgentTool(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListAgentTools(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateAgentTool(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteAgentTool(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AgentToolControllerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateAgentTool': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateAgentTool,
                    request_deserializer=AgentTool__pb2.CreateAgentToolRequest.FromString,
                    response_serializer=AgentTool__pb2.CreateAgentToolResponse.SerializeToString,
            ),
            'GetAgentTool': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAgentTool,
                    request_deserializer=AgentTool__pb2.GetAgentToolRequest.FromString,
                    response_serializer=AgentTool__pb2.GetAgentToolResponse.SerializeToString,
            ),
            'ListAgentTools': grpc.unary_unary_rpc_method_handler(
                    servicer.ListAgentTools,
                    request_deserializer=AgentTool__pb2.ListAgentToolsRequest.FromString,
                    response_serializer=AgentTool__pb2.ListAgentToolsResponse.SerializeToString,
            ),
            'UpdateAgentTool': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateAgentTool,
                    request_deserializer=AgentTool__pb2.UpdateAgentToolRequest.FromString,
                    response_serializer=AgentTool__pb2.UpdateAgentToolResponse.SerializeToString,
            ),
            'DeleteAgentTool': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteAgentTool,
                    request_deserializer=AgentTool__pb2.DeleteAgentToolRequest.FromString,
                    response_serializer=AgentTool__pb2.DeleteAgentToolResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pb.AgentToolController', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AgentToolController(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateAgentTool(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pb.AgentToolController/CreateAgentTool',
            AgentTool__pb2.CreateAgentToolRequest.SerializeToString,
            AgentTool__pb2.CreateAgentToolResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetAgentTool(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pb.AgentToolController/GetAgentTool',
            AgentTool__pb2.GetAgentToolRequest.SerializeToString,
            AgentTool__pb2.GetAgentToolResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListAgentTools(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pb.AgentToolController/ListAgentTools',
            AgentTool__pb2.ListAgentToolsRequest.SerializeToString,
            AgentTool__pb2.ListAgentToolsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateAgentTool(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pb.AgentToolController/UpdateAgentTool',
            AgentTool__pb2.UpdateAgentToolRequest.SerializeToString,
            AgentTool__pb2.UpdateAgentToolResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteAgentTool(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pb.AgentToolController/DeleteAgentTool',
            AgentTool__pb2.DeleteAgentToolRequest.SerializeToString,
            AgentTool__pb2.DeleteAgentToolResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
