# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: AgentTool.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
import core_app.grpc.pb.UUID_pb2 as UUID__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x41gentTool.proto\x12\x02pb\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\nUUID.proto\"\xbe\x01\n\tAgentTool\x12\x14\n\x02id\x18\x01 \x01(\x0b\x32\x08.pb.UUID\x12\x11\n\ttool_name\x18\x02 \x01(\t\x12\x13\n\x0b\x61rgs_schema\x18\x03 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x04 \x01(\t\x12.\n\ncreated_at\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12.\n\nupdated_at\x18\x06 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\":\n\x16\x43reateAgentToolRequest\x12 \n\tagenttool\x18\x01 \x01(\x0b\x32\r.pb.AgentTool\"/\n\x17\x43reateAgentToolResponse\x12\x14\n\x02id\x18\x01 \x01(\x0b\x32\x08.pb.UUID\"+\n\x13GetAgentToolRequest\x12\x14\n\x02id\x18\x01 \x01(\x0b\x32\x08.pb.UUID\"8\n\x14GetAgentToolResponse\x12 \n\tagenttool\x18\x01 \x01(\x0b\x32\r.pb.AgentTool\"\x17\n\x15ListAgentToolsRequest\";\n\x16ListAgentToolsResponse\x12!\n\nagenttools\x18\x01 \x03(\x0b\x32\r.pb.AgentTool\":\n\x16UpdateAgentToolRequest\x12 \n\tagenttool\x18\x01 \x01(\x0b\x32\r.pb.AgentTool\"\x19\n\x17UpdateAgentToolResponse\".\n\x16\x44\x65leteAgentToolRequest\x12\x14\n\x02id\x18\x01 \x01(\x0b\x32\x08.pb.UUID\"\x19\n\x17\x44\x65leteAgentToolResponse2\x8f\x03\n\x13\x41gentToolController\x12L\n\x0f\x43reateAgentTool\x12\x1a.pb.CreateAgentToolRequest\x1a\x1b.pb.CreateAgentToolResponse\"\x00\x12\x43\n\x0cGetAgentTool\x12\x17.pb.GetAgentToolRequest\x1a\x18.pb.GetAgentToolResponse\"\x00\x12I\n\x0eListAgentTools\x12\x19.pb.ListAgentToolsRequest\x1a\x1a.pb.ListAgentToolsResponse\"\x00\x12L\n\x0fUpdateAgentTool\x12\x1a.pb.UpdateAgentToolRequest\x1a\x1b.pb.UpdateAgentToolResponse\"\x00\x12L\n\x0f\x44\x65leteAgentTool\x12\x1a.pb.DeleteAgentToolRequest\x1a\x1b.pb.DeleteAgentToolResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'AgentTool_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_AGENTTOOL']._serialized_start=69
  _globals['_AGENTTOOL']._serialized_end=259
  _globals['_CREATEAGENTTOOLREQUEST']._serialized_start=261
  _globals['_CREATEAGENTTOOLREQUEST']._serialized_end=319
  _globals['_CREATEAGENTTOOLRESPONSE']._serialized_start=321
  _globals['_CREATEAGENTTOOLRESPONSE']._serialized_end=368
  _globals['_GETAGENTTOOLREQUEST']._serialized_start=370
  _globals['_GETAGENTTOOLREQUEST']._serialized_end=413
  _globals['_GETAGENTTOOLRESPONSE']._serialized_start=415
  _globals['_GETAGENTTOOLRESPONSE']._serialized_end=471
  _globals['_LISTAGENTTOOLSREQUEST']._serialized_start=473
  _globals['_LISTAGENTTOOLSREQUEST']._serialized_end=496
  _globals['_LISTAGENTTOOLSRESPONSE']._serialized_start=498
  _globals['_LISTAGENTTOOLSRESPONSE']._serialized_end=557
  _globals['_UPDATEAGENTTOOLREQUEST']._serialized_start=559
  _globals['_UPDATEAGENTTOOLREQUEST']._serialized_end=617
  _globals['_UPDATEAGENTTOOLRESPONSE']._serialized_start=619
  _globals['_UPDATEAGENTTOOLRESPONSE']._serialized_end=644
  _globals['_DELETEAGENTTOOLREQUEST']._serialized_start=646
  _globals['_DELETEAGENTTOOLREQUEST']._serialized_end=692
  _globals['_DELETEAGENTTOOLRESPONSE']._serialized_start=694
  _globals['_DELETEAGENTTOOLRESPONSE']._serialized_end=719
  _globals['_AGENTTOOLCONTROLLER']._serialized_start=722
  _globals['_AGENTTOOLCONTROLLER']._serialized_end=1121
# @@protoc_insertion_point(module_scope)
