# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import core_app.grpc.pb.ExternalKownledge_pb2 as ExternalKownledge__pb2


class ExternalKnowledgeControllerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateExternalKnowledge = channel.unary_unary(
                '/pb.ExternalKnowledgeController/CreateExternalKnowledge',
                request_serializer=ExternalKownledge__pb2.CreateExternalKnowledgeRequest.SerializeToString,
                response_deserializer=ExternalKownledge__pb2.CreateExternalKnowledgeResponse.FromString,
                )
        self.GetExternalKnowledge = channel.unary_unary(
                '/pb.ExternalKnowledgeController/GetExternalKnowledge',
                request_serializer=ExternalKownledge__pb2.GetExternalKnowledgeRequest.SerializeToString,
                response_deserializer=ExternalKownledge__pb2.GetExternalKnowledgeResponse.FromString,
                )
        self.ListExternalKnowledges = channel.unary_unary(
                '/pb.ExternalKnowledgeController/ListExternalKnowledges',
                request_serializer=ExternalKownledge__pb2.ListExternalKnowledgesRequest.SerializeToString,
                response_deserializer=ExternalKownledge__pb2.ListExternalKnowledgesResponse.FromString,
                )
        self.UpdateExternalKnowledge = channel.unary_unary(
                '/pb.ExternalKnowledgeController/UpdateExternalKnowledge',
                request_serializer=ExternalKownledge__pb2.UpdateExternalKnowledgeRequest.SerializeToString,
                response_deserializer=ExternalKownledge__pb2.UpdateExternalKnowledgeResponse.FromString,
                )
        self.DeleteExternalKnowledge = channel.unary_unary(
                '/pb.ExternalKnowledgeController/DeleteExternalKnowledge',
                request_serializer=ExternalKownledge__pb2.DeleteExternalKnowledgeRequest.SerializeToString,
                response_deserializer=ExternalKownledge__pb2.DeleteExternalKnowledgeResponse.FromString,
                )


class ExternalKnowledgeControllerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateExternalKnowledge(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetExternalKnowledge(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListExternalKnowledges(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateExternalKnowledge(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteExternalKnowledge(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ExternalKnowledgeControllerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateExternalKnowledge': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateExternalKnowledge,
                    request_deserializer=ExternalKownledge__pb2.CreateExternalKnowledgeRequest.FromString,
                    response_serializer=ExternalKownledge__pb2.CreateExternalKnowledgeResponse.SerializeToString,
            ),
            'GetExternalKnowledge': grpc.unary_unary_rpc_method_handler(
                    servicer.GetExternalKnowledge,
                    request_deserializer=ExternalKownledge__pb2.GetExternalKnowledgeRequest.FromString,
                    response_serializer=ExternalKownledge__pb2.GetExternalKnowledgeResponse.SerializeToString,
            ),
            'ListExternalKnowledges': grpc.unary_unary_rpc_method_handler(
                    servicer.ListExternalKnowledges,
                    request_deserializer=ExternalKownledge__pb2.ListExternalKnowledgesRequest.FromString,
                    response_serializer=ExternalKownledge__pb2.ListExternalKnowledgesResponse.SerializeToString,
            ),
            'UpdateExternalKnowledge': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateExternalKnowledge,
                    request_deserializer=ExternalKownledge__pb2.UpdateExternalKnowledgeRequest.FromString,
                    response_serializer=ExternalKownledge__pb2.UpdateExternalKnowledgeResponse.SerializeToString,
            ),
            'DeleteExternalKnowledge': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteExternalKnowledge,
                    request_deserializer=ExternalKownledge__pb2.DeleteExternalKnowledgeRequest.FromString,
                    response_serializer=ExternalKownledge__pb2.DeleteExternalKnowledgeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pb.ExternalKnowledgeController', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ExternalKnowledgeController(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateExternalKnowledge(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pb.ExternalKnowledgeController/CreateExternalKnowledge',
            ExternalKownledge__pb2.CreateExternalKnowledgeRequest.SerializeToString,
            ExternalKownledge__pb2.CreateExternalKnowledgeResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetExternalKnowledge(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pb.ExternalKnowledgeController/GetExternalKnowledge',
            ExternalKownledge__pb2.GetExternalKnowledgeRequest.SerializeToString,
            ExternalKownledge__pb2.GetExternalKnowledgeResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListExternalKnowledges(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pb.ExternalKnowledgeController/ListExternalKnowledges',
            ExternalKownledge__pb2.ListExternalKnowledgesRequest.SerializeToString,
            ExternalKownledge__pb2.ListExternalKnowledgesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateExternalKnowledge(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pb.ExternalKnowledgeController/UpdateExternalKnowledge',
            ExternalKownledge__pb2.UpdateExternalKnowledgeRequest.SerializeToString,
            ExternalKownledge__pb2.UpdateExternalKnowledgeResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteExternalKnowledge(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pb.ExternalKnowledgeController/DeleteExternalKnowledge',
            ExternalKownledge__pb2.DeleteExternalKnowledgeRequest.SerializeToString,
            ExternalKownledge__pb2.DeleteExternalKnowledgeResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
