# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import core_app.grpc.pb.InternalKownledge_pb2 as InternalKownledge__pb2


class InternalKnowledgeControllerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateInternalKnowledge = channel.unary_unary(
                '/pb.InternalKnowledgeController/CreateInternalKnowledge',
                request_serializer=InternalKownledge__pb2.CreateInternalKnowledgeRequest.SerializeToString,
                response_deserializer=InternalKownledge__pb2.CreateInternalKnowledgeResponse.FromString,
                )
        self.GetInternalKnowledge = channel.unary_unary(
                '/pb.InternalKnowledgeController/GetInternalKnowledge',
                request_serializer=InternalKownledge__pb2.GetInternalKnowledgeRequest.SerializeToString,
                response_deserializer=InternalKownledge__pb2.GetInternalKnowledgeResponse.FromString,
                )
        self.ListInternalKnowledges = channel.unary_unary(
                '/pb.InternalKnowledgeController/ListInternalKnowledges',
                request_serializer=InternalKownledge__pb2.ListInternalKnowledgesRequest.SerializeToString,
                response_deserializer=InternalKownledge__pb2.ListInternalKnowledgesResponse.FromString,
                )
        self.UpdateInternalKnowledge = channel.unary_unary(
                '/pb.InternalKnowledgeController/UpdateInternalKnowledge',
                request_serializer=InternalKownledge__pb2.UpdateInternalKnowledgeRequest.SerializeToString,
                response_deserializer=InternalKownledge__pb2.UpdateInternalKnowledgeResponse.FromString,
                )
        self.DeleteInternalKnowledge = channel.unary_unary(
                '/pb.InternalKnowledgeController/DeleteInternalKnowledge',
                request_serializer=InternalKownledge__pb2.DeleteInternalKnowledgeRequest.SerializeToString,
                response_deserializer=InternalKownledge__pb2.DeleteInternalKnowledgeResponse.FromString,
                )


class InternalKnowledgeControllerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateInternalKnowledge(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetInternalKnowledge(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListInternalKnowledges(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateInternalKnowledge(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteInternalKnowledge(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_InternalKnowledgeControllerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateInternalKnowledge': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateInternalKnowledge,
                    request_deserializer=InternalKownledge__pb2.CreateInternalKnowledgeRequest.FromString,
                    response_serializer=InternalKownledge__pb2.CreateInternalKnowledgeResponse.SerializeToString,
            ),
            'GetInternalKnowledge': grpc.unary_unary_rpc_method_handler(
                    servicer.GetInternalKnowledge,
                    request_deserializer=InternalKownledge__pb2.GetInternalKnowledgeRequest.FromString,
                    response_serializer=InternalKownledge__pb2.GetInternalKnowledgeResponse.SerializeToString,
            ),
            'ListInternalKnowledges': grpc.unary_unary_rpc_method_handler(
                    servicer.ListInternalKnowledges,
                    request_deserializer=InternalKownledge__pb2.ListInternalKnowledgesRequest.FromString,
                    response_serializer=InternalKownledge__pb2.ListInternalKnowledgesResponse.SerializeToString,
            ),
            'UpdateInternalKnowledge': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateInternalKnowledge,
                    request_deserializer=InternalKownledge__pb2.UpdateInternalKnowledgeRequest.FromString,
                    response_serializer=InternalKownledge__pb2.UpdateInternalKnowledgeResponse.SerializeToString,
            ),
            'DeleteInternalKnowledge': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteInternalKnowledge,
                    request_deserializer=InternalKownledge__pb2.DeleteInternalKnowledgeRequest.FromString,
                    response_serializer=InternalKownledge__pb2.DeleteInternalKnowledgeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pb.InternalKnowledgeController', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class InternalKnowledgeController(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateInternalKnowledge(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pb.InternalKnowledgeController/CreateInternalKnowledge',
            InternalKownledge__pb2.CreateInternalKnowledgeRequest.SerializeToString,
            InternalKownledge__pb2.CreateInternalKnowledgeResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetInternalKnowledge(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pb.InternalKnowledgeController/GetInternalKnowledge',
            InternalKownledge__pb2.GetInternalKnowledgeRequest.SerializeToString,
            InternalKownledge__pb2.GetInternalKnowledgeResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListInternalKnowledges(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pb.InternalKnowledgeController/ListInternalKnowledges',
            InternalKownledge__pb2.ListInternalKnowledgesRequest.SerializeToString,
            InternalKownledge__pb2.ListInternalKnowledgesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateInternalKnowledge(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pb.InternalKnowledgeController/UpdateInternalKnowledge',
            InternalKownledge__pb2.UpdateInternalKnowledgeRequest.SerializeToString,
            InternalKownledge__pb2.UpdateInternalKnowledgeResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteInternalKnowledge(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pb.InternalKnowledgeController/DeleteInternalKnowledge',
            InternalKownledge__pb2.DeleteInternalKnowledgeRequest.SerializeToString,
            InternalKownledge__pb2.DeleteInternalKnowledgeResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
