# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import core_app.grpc.pb.LlmModel_pb2 as LlmModel__pb2


class LlmModelControllerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateLlmModel = channel.unary_unary(
                '/pb.LlmModelController/CreateLlmModel',
                request_serializer=LlmModel__pb2.CreateLlmModelRequest.SerializeToString,
                response_deserializer=LlmModel__pb2.CreateLlmModelResponse.FromString,
                )
        self.GetLlmModel = channel.unary_unary(
                '/pb.LlmModelController/GetLlmModel',
                request_serializer=LlmModel__pb2.GetLlmModelRequest.SerializeToString,
                response_deserializer=LlmModel__pb2.GetLlmModelResponse.FromString,
                )
        self.ListLlmModels = channel.unary_unary(
                '/pb.LlmModelController/ListLlmModels',
                request_serializer=LlmModel__pb2.ListLlmModelsRequest.SerializeToString,
                response_deserializer=LlmModel__pb2.ListLlmModelsResponse.FromString,
                )
        self.UpdateLlmModel = channel.unary_unary(
                '/pb.LlmModelController/UpdateLlmModel',
                request_serializer=LlmModel__pb2.UpdateLlmModelRequest.SerializeToString,
                response_deserializer=LlmModel__pb2.UpdateLlmModelResponse.FromString,
                )
        self.DeleteLlmModel = channel.unary_unary(
                '/pb.LlmModelController/DeleteLlmModel',
                request_serializer=LlmModel__pb2.DeleteLlmModelRequest.SerializeToString,
                response_deserializer=LlmModel__pb2.DeleteLlmModelResponse.FromString,
                )


class LlmModelControllerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateLlmModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLlmModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListLlmModels(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateLlmModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteLlmModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LlmModelControllerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateLlmModel': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateLlmModel,
                    request_deserializer=LlmModel__pb2.CreateLlmModelRequest.FromString,
                    response_serializer=LlmModel__pb2.CreateLlmModelResponse.SerializeToString,
            ),
            'GetLlmModel': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLlmModel,
                    request_deserializer=LlmModel__pb2.GetLlmModelRequest.FromString,
                    response_serializer=LlmModel__pb2.GetLlmModelResponse.SerializeToString,
            ),
            'ListLlmModels': grpc.unary_unary_rpc_method_handler(
                    servicer.ListLlmModels,
                    request_deserializer=LlmModel__pb2.ListLlmModelsRequest.FromString,
                    response_serializer=LlmModel__pb2.ListLlmModelsResponse.SerializeToString,
            ),
            'UpdateLlmModel': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateLlmModel,
                    request_deserializer=LlmModel__pb2.UpdateLlmModelRequest.FromString,
                    response_serializer=LlmModel__pb2.UpdateLlmModelResponse.SerializeToString,
            ),
            'DeleteLlmModel': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteLlmModel,
                    request_deserializer=LlmModel__pb2.DeleteLlmModelRequest.FromString,
                    response_serializer=LlmModel__pb2.DeleteLlmModelResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pb.LlmModelController', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class LlmModelController(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateLlmModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pb.LlmModelController/CreateLlmModel',
            LlmModel__pb2.CreateLlmModelRequest.SerializeToString,
            LlmModel__pb2.CreateLlmModelResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetLlmModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pb.LlmModelController/GetLlmModel',
            LlmModel__pb2.GetLlmModelRequest.SerializeToString,
            LlmModel__pb2.GetLlmModelResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListLlmModels(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pb.LlmModelController/ListLlmModels',
            LlmModel__pb2.ListLlmModelsRequest.SerializeToString,
            LlmModel__pb2.ListLlmModelsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateLlmModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pb.LlmModelController/UpdateLlmModel',
            LlmModel__pb2.UpdateLlmModelRequest.SerializeToString,
            LlmModel__pb2.UpdateLlmModelResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteLlmModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pb.LlmModelController/DeleteLlmModel',
            LlmModel__pb2.DeleteLlmModelRequest.SerializeToString,
            LlmModel__pb2.DeleteLlmModelResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
