# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ocr_service.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11ocr_service.proto\x12\x02pb\".\n\x0b\x46ileRequest\x12\x11\n\tfile_name\x18\x01 \x01(\t\x12\x0c\n\x04\x66ile\x18\x02 \x01(\x0c\"O\n\x0c\x46ileResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x0c\n\x04text\x18\x02 \x01(\t\x12 \n\ttranslate\x18\x03 \x01(\x0b\x32\r.pb.translate\";\n\ttranslate\x12\n\n\x02\x65n\x18\x01 \x01(\t\x12\n\n\x02vi\x18\x02 \x01(\t\x12\n\n\x02ko\x18\x03 \x01(\t\x12\n\n\x02ja\x18\x04 \x01(\t2G\n\nOCRService\x12\x39\n\x12\x43reateTextFromFile\x12\x0f.pb.FileRequest\x1a\x10.pb.FileResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ocr_service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_FILEREQUEST']._serialized_start=25
  _globals['_FILEREQUEST']._serialized_end=71
  _globals['_FILERESPONSE']._serialized_start=73
  _globals['_FILERESPONSE']._serialized_end=152
  _globals['_TRANSLATE']._serialized_start=154
  _globals['_TRANSLATE']._serialized_end=213
  _globals['_OCRSERVICE']._serialized_start=215
  _globals['_OCRSERVICE']._serialized_end=286
# @@protoc_insertion_point(module_scope)
