# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: stt_service.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11stt_service.proto\x12\x02pb\"%\n\x10\x41udioFileRequest\x12\x11\n\tfile_data\x18\x01 \x01(\x0c\".\n\x15TranscriptionResponse\x12\x15\n\rtranscription\x18\x01 \x01(\t\"\'\n\x11\x41udioChunkRequest\x12\x12\n\nchunk_data\x18\x01 \x01(\x0c\"7\n\x1eTranscriptionStreamingResponse\x12\x15\n\rtranscription\x18\x01 \x01(\t2\x9a\x01\n\nSTTService\x12>\n\x0bUploadAudio\x12\x14.pb.AudioFileRequest\x1a\x19.pb.TranscriptionResponse\x12L\n\x0bStreamAudio\x12\x15.pb.AudioChunkRequest\x1a\".pb.TranscriptionStreamingResponse(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stt_service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_AUDIOFILEREQUEST']._serialized_start=25
  _globals['_AUDIOFILEREQUEST']._serialized_end=62
  _globals['_TRANSCRIPTIONRESPONSE']._serialized_start=64
  _globals['_TRANSCRIPTIONRESPONSE']._serialized_end=110
  _globals['_AUDIOCHUNKREQUEST']._serialized_start=112
  _globals['_AUDIOCHUNKREQUEST']._serialized_end=151
  _globals['_TRANSCRIPTIONSTREAMINGRESPONSE']._serialized_start=153
  _globals['_TRANSCRIPTIONSTREAMINGRESPONSE']._serialized_end=208
  _globals['_STTSERVICE']._serialized_start=211
  _globals['_STTSERVICE']._serialized_end=365
# @@protoc_insertion_point(module_scope)
