# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import core_app.grpc.pb.SystemPrompt_pb2 as SystemPrompt__pb2


class SystemPromptControllerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateSystemPrompt = channel.unary_unary(
                '/pb.SystemPromptController/CreateSystemPrompt',
                request_serializer=SystemPrompt__pb2.CreateSystemPromptRequest.SerializeToString,
                response_deserializer=SystemPrompt__pb2.CreateSystemPromptResponse.FromString,
                )
        self.GetSystemPrompt = channel.unary_unary(
                '/pb.SystemPromptController/GetSystemPrompt',
                request_serializer=SystemPrompt__pb2.GetSystemPromptRequest.SerializeToString,
                response_deserializer=SystemPrompt__pb2.GetSystemPromptResponse.FromString,
                )
        self.ListSystemPrompts = channel.unary_unary(
                '/pb.SystemPromptController/ListSystemPrompts',
                request_serializer=SystemPrompt__pb2.ListSystemPromptsRequest.SerializeToString,
                response_deserializer=SystemPrompt__pb2.ListSystemPromptsResponse.FromString,
                )
        self.UpdateSystemPrompt = channel.unary_unary(
                '/pb.SystemPromptController/UpdateSystemPrompt',
                request_serializer=SystemPrompt__pb2.UpdateSystemPromptRequest.SerializeToString,
                response_deserializer=SystemPrompt__pb2.UpdateSystemPromptResponse.FromString,
                )
        self.DeleteSystemPrompt = channel.unary_unary(
                '/pb.SystemPromptController/DeleteSystemPrompt',
                request_serializer=SystemPrompt__pb2.DeleteSystemPromptRequest.SerializeToString,
                response_deserializer=SystemPrompt__pb2.DeleteSystemPromptResponse.FromString,
                )


class SystemPromptControllerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateSystemPrompt(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSystemPrompt(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListSystemPrompts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateSystemPrompt(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteSystemPrompt(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SystemPromptControllerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateSystemPrompt': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateSystemPrompt,
                    request_deserializer=SystemPrompt__pb2.CreateSystemPromptRequest.FromString,
                    response_serializer=SystemPrompt__pb2.CreateSystemPromptResponse.SerializeToString,
            ),
            'GetSystemPrompt': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSystemPrompt,
                    request_deserializer=SystemPrompt__pb2.GetSystemPromptRequest.FromString,
                    response_serializer=SystemPrompt__pb2.GetSystemPromptResponse.SerializeToString,
            ),
            'ListSystemPrompts': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSystemPrompts,
                    request_deserializer=SystemPrompt__pb2.ListSystemPromptsRequest.FromString,
                    response_serializer=SystemPrompt__pb2.ListSystemPromptsResponse.SerializeToString,
            ),
            'UpdateSystemPrompt': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateSystemPrompt,
                    request_deserializer=SystemPrompt__pb2.UpdateSystemPromptRequest.FromString,
                    response_serializer=SystemPrompt__pb2.UpdateSystemPromptResponse.SerializeToString,
            ),
            'DeleteSystemPrompt': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteSystemPrompt,
                    request_deserializer=SystemPrompt__pb2.DeleteSystemPromptRequest.FromString,
                    response_serializer=SystemPrompt__pb2.DeleteSystemPromptResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pb.SystemPromptController', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SystemPromptController(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateSystemPrompt(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pb.SystemPromptController/CreateSystemPrompt',
            SystemPrompt__pb2.CreateSystemPromptRequest.SerializeToString,
            SystemPrompt__pb2.CreateSystemPromptResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetSystemPrompt(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pb.SystemPromptController/GetSystemPrompt',
            SystemPrompt__pb2.GetSystemPromptRequest.SerializeToString,
            SystemPrompt__pb2.GetSystemPromptResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListSystemPrompts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pb.SystemPromptController/ListSystemPrompts',
            SystemPrompt__pb2.ListSystemPromptsRequest.SerializeToString,
            SystemPrompt__pb2.ListSystemPromptsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateSystemPrompt(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pb.SystemPromptController/UpdateSystemPrompt',
            SystemPrompt__pb2.UpdateSystemPromptRequest.SerializeToString,
            SystemPrompt__pb2.UpdateSystemPromptResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteSystemPrompt(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pb.SystemPromptController/DeleteSystemPrompt',
            SystemPrompt__pb2.DeleteSystemPromptRequest.SerializeToString,
            SystemPrompt__pb2.DeleteSystemPromptResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
