# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SystemPrompt.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
import core_app.grpc.pb.UUID_pb2 as UUID__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12SystemPrompt.proto\x12\x02pb\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\nUUID.proto\"\xb1\x01\n\x0cSystemPrompt\x12\x14\n\x02id\x18\x01 \x01(\x0b\x32\x08.pb.UUID\x12.\n\ncreated_at\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12.\n\nupdated_at\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x13\n\x0bprompt_name\x18\x04 \x01(\t\x12\x16\n\x0eprompt_content\x18\x05 \x01(\t\"C\n\x19\x43reateSystemPromptRequest\x12&\n\x0csystemprompt\x18\x01 \x01(\x0b\x32\x10.pb.SystemPrompt\"2\n\x1a\x43reateSystemPromptResponse\x12\x14\n\x02id\x18\x01 \x01(\x0b\x32\x08.pb.UUID\".\n\x16GetSystemPromptRequest\x12\x14\n\x02id\x18\x01 \x01(\x0b\x32\x08.pb.UUID\"A\n\x17GetSystemPromptResponse\x12&\n\x0csystemprompt\x18\x01 \x01(\x0b\x32\x10.pb.SystemPrompt\"\x1a\n\x18ListSystemPromptsRequest\"D\n\x19ListSystemPromptsResponse\x12\'\n\rsystemprompts\x18\x01 \x03(\x0b\x32\x10.pb.SystemPrompt\"C\n\x19UpdateSystemPromptRequest\x12&\n\x0csystemprompt\x18\x01 \x01(\x0b\x32\x10.pb.SystemPrompt\"\x1c\n\x1aUpdateSystemPromptResponse\"1\n\x19\x44\x65leteSystemPromptRequest\x12\x14\n\x02id\x18\x01 \x01(\x0b\x32\x08.pb.UUID\"\x1c\n\x1a\x44\x65leteSystemPromptResponse2\xbf\x03\n\x16SystemPromptController\x12U\n\x12\x43reateSystemPrompt\x12\x1d.pb.CreateSystemPromptRequest\x1a\x1e.pb.CreateSystemPromptResponse\"\x00\x12L\n\x0fGetSystemPrompt\x12\x1a.pb.GetSystemPromptRequest\x1a\x1b.pb.GetSystemPromptResponse\"\x00\x12R\n\x11ListSystemPrompts\x12\x1c.pb.ListSystemPromptsRequest\x1a\x1d.pb.ListSystemPromptsResponse\"\x00\x12U\n\x12UpdateSystemPrompt\x12\x1d.pb.UpdateSystemPromptRequest\x1a\x1e.pb.UpdateSystemPromptResponse\"\x00\x12U\n\x12\x44\x65leteSystemPrompt\x12\x1d.pb.DeleteSystemPromptRequest\x1a\x1e.pb.DeleteSystemPromptResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'SystemPrompt_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_SYSTEMPROMPT']._serialized_start=72
  _globals['_SYSTEMPROMPT']._serialized_end=249
  _globals['_CREATESYSTEMPROMPTREQUEST']._serialized_start=251
  _globals['_CREATESYSTEMPROMPTREQUEST']._serialized_end=318
  _globals['_CREATESYSTEMPROMPTRESPONSE']._serialized_start=320
  _globals['_CREATESYSTEMPROMPTRESPONSE']._serialized_end=370
  _globals['_GETSYSTEMPROMPTREQUEST']._serialized_start=372
  _globals['_GETSYSTEMPROMPTREQUEST']._serialized_end=418
  _globals['_GETSYSTEMPROMPTRESPONSE']._serialized_start=420
  _globals['_GETSYSTEMPROMPTRESPONSE']._serialized_end=485
  _globals['_LISTSYSTEMPROMPTSREQUEST']._serialized_start=487
  _globals['_LISTSYSTEMPROMPTSREQUEST']._serialized_end=513
  _globals['_LISTSYSTEMPROMPTSRESPONSE']._serialized_start=515
  _globals['_LISTSYSTEMPROMPTSRESPONSE']._serialized_end=583
  _globals['_UPDATESYSTEMPROMPTREQUEST']._serialized_start=585
  _globals['_UPDATESYSTEMPROMPTREQUEST']._serialized_end=652
  _globals['_UPDATESYSTEMPROMPTRESPONSE']._serialized_start=654
  _globals['_UPDATESYSTEMPROMPTRESPONSE']._serialized_end=682
  _globals['_DELETESYSTEMPROMPTREQUEST']._serialized_start=684
  _globals['_DELETESYSTEMPROMPTREQUEST']._serialized_end=733
  _globals['_DELETESYSTEMPROMPTRESPONSE']._serialized_start=735
  _globals['_DELETESYSTEMPROMPTRESPONSE']._serialized_end=763
  _globals['_SYSTEMPROMPTCONTROLLER']._serialized_start=766
  _globals['_SYSTEMPROMPTCONTROLLER']._serialized_end=1213
# @@protoc_insertion_point(module_scope)
