# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: User.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import core_app.grpc.pb.UUID_pb2 as UUID__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nUser.proto\x12\x02pb\x1a\nUUID.proto\"O\n\x04User\x12\x14\n\x02id\x18\x01 \x01(\x0b\x32\x08.pb.UUID\x12\x10\n\x08password\x18\x02 \x01(\t\x12\x10\n\x08username\x18\x03 \x01(\t\x12\r\n\x05\x65mail\x18\x04 \x01(\t\"+\n\x11\x43reateUserRequest\x12\x16\n\x04user\x18\x01 \x01(\x0b\x32\x08.pb.User\"*\n\x12\x43reateUserResponse\x12\x14\n\x02id\x18\x01 \x01(\x0b\x32\x08.pb.UUID\"&\n\x0eGetUserRequest\x12\x14\n\x02id\x18\x01 \x01(\x0b\x32\x08.pb.UUID\")\n\x0fGetUserResponse\x12\x16\n\x04user\x18\x01 \x01(\x0b\x32\x08.pb.User\"\x12\n\x10ListUsersRequest\",\n\x11ListUsersResponse\x12\x17\n\x05users\x18\x01 \x03(\x0b\x32\x08.pb.User\"+\n\x11UpdateUserRequest\x12\x16\n\x04user\x18\x01 \x01(\x0b\x32\x08.pb.User\"\x14\n\x12UpdateUserResponse\")\n\x11\x44\x65leteUserRequest\x12\x14\n\x02id\x18\x01 \x01(\x0b\x32\x08.pb.UUID\"\x14\n\x12\x44\x65leteUserResponse2\xbf\x02\n\x0eUserController\x12=\n\nCreateUser\x12\x15.pb.CreateUserRequest\x1a\x16.pb.CreateUserResponse\"\x00\x12\x34\n\x07GetUser\x12\x12.pb.GetUserRequest\x1a\x13.pb.GetUserResponse\"\x00\x12:\n\tListUsers\x12\x14.pb.ListUsersRequest\x1a\x15.pb.ListUsersResponse\"\x00\x12=\n\nUpdateUser\x12\x15.pb.UpdateUserRequest\x1a\x16.pb.UpdateUserResponse\"\x00\x12=\n\nDeleteUser\x12\x15.pb.DeleteUserRequest\x1a\x16.pb.DeleteUserResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'User_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_USER']._serialized_start=30
  _globals['_USER']._serialized_end=109
  _globals['_CREATEUSERREQUEST']._serialized_start=111
  _globals['_CREATEUSERREQUEST']._serialized_end=154
  _globals['_CREATEUSERRESPONSE']._serialized_start=156
  _globals['_CREATEUSERRESPONSE']._serialized_end=198
  _globals['_GETUSERREQUEST']._serialized_start=200
  _globals['_GETUSERREQUEST']._serialized_end=238
  _globals['_GETUSERRESPONSE']._serialized_start=240
  _globals['_GETUSERRESPONSE']._serialized_end=281
  _globals['_LISTUSERSREQUEST']._serialized_start=283
  _globals['_LISTUSERSREQUEST']._serialized_end=301
  _globals['_LISTUSERSRESPONSE']._serialized_start=303
  _globals['_LISTUSERSRESPONSE']._serialized_end=347
  _globals['_UPDATEUSERREQUEST']._serialized_start=349
  _globals['_UPDATEUSERREQUEST']._serialized_end=392
  _globals['_UPDATEUSERRESPONSE']._serialized_start=394
  _globals['_UPDATEUSERRESPONSE']._serialized_end=414
  _globals['_DELETEUSERREQUEST']._serialized_start=416
  _globals['_DELETEUSERREQUEST']._serialized_end=457
  _globals['_DELETEUSERRESPONSE']._serialized_start=459
  _globals['_DELETEUSERRESPONSE']._serialized_end=479
  _globals['_USERCONTROLLER']._serialized_start=482
  _globals['_USERCONTROLLER']._serialized_end=801
# @@protoc_insertion_point(module_scope)
