POST  http://127.0.0.1:8000/conversation/
Content-Type: application/json

{
    "prompt_name": "teacher",
    "gpt_model": "openai"
POST http://127.0.0.1:8000/answer/
Content-Type: application/json

{
    "conversation_id": 6,
    "message": "who are you ?"
}

###
POST  http://127.0.0.1:8000/system-prompt/
Content-Type: application/json

{
    "character": "teacher",
    "prompt": "....."
}

###
POST http://127.0.0.1:8000/agent/
Content-Type: application/json

{
    "conversation_id": "1",
    "message": "hello there"
}
    "expert_name": "ethic",
    "gpt_model": "openai"
}
