POST http://127.0.0.1:8000/agent/
Content-Type: application/json

{
    "conversation_id": "1",
    "message": "hello there"
}

####
GET http://127.0.0.1:8000/conversation/
Content-Type: application/json
