# Generated by Django 4.2 on 2024-07-15 03:44

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('prompt_name', models.CharField(max_length=100)),
                ('gpt_model', models.CharField(max_length=100)),
                ('chat_history', django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), default=list, size=None)),
                ('meta_data', models.JSONField(blank=True, default=dict, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=100)),
                ('chapter', models.CharField(max_length=100)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SystemPrompt',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('character', models.CharField(max_length=100, unique=True)),
                ('prompt', models.TextField()),
            ],
        ),
    ]
