# Generated by Django 4.2 on 2024-10-23 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facedata',
            name='subsystem',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
