# Generated by Django 4.2 on 2024-11-04 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0002_facedata_subsystem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facedata',
            name='gender',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
