# Generated by Django 4.2 on 2024-08-17 12:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core_app', '0002_remove_agenttool_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='agent',
            unique_together={('agent_name', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='llmmodel',
            unique_together={('llm_name', 'user')},
        ),
    ]
