# Generated by Django 4.2 on 2024-07-17 07:08

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0002_alter_conversation_chat_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='chat_history',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), default=list, size=None),
        ),
    ]
