# Generated by Django 4.2 on 2024-07-17 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0003_alter_conversation_chat_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='knowledge',
            field=models.TextField(blank=True, null=True),
        ),
    ]
