# Generated by Django 4.2 on 2024-11-04 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0003_alter_facedata_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facedata',
            name='age',
        ),
        migrations.RemoveField(
            model_name='facedata',
            name='birthday',
        ),
        migrations.RemoveField(
            model_name='facedata',
            name='country',
        ),
        migrations.RemoveField(
            model_name='facedata',
            name='email',
        ),
        migrations.RemoveField(
            model_name='facedata',
            name='phone_number',
        ),
    ]
