# Generated by Django 4.2 on 2024-07-17 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0004_conversation_knowledge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='knowledge',
            field=models.TextField(blank=True, default=dict),
        ),
    ]
