# Generated by Django 4.2 on 2024-07-17 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0006_alter_conversation_knowledge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='knowledge',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
